// src/components/PromptList.vue
<template>
  <section :class="$style.promptList">
    <PromptListItem
      v-for="(item, index) in prompts"
      :key="index"
      :active="selectedIndex === index"
      :class="$style.propmtItem"
      :title="item.title"
      @click="() => handleSelectPropmt(index)"
      @on-edit="() => handleEditPrompt(index)"
    />

    <PromptListItem :active="false" :class="$style.propmtItem" title="+" @click="handleAddPrompt" />
  </section>
</template>

<script setup>
import {toRaw} from 'vue'

import PromptListItem from './PromptListItem.vue'

const emits = defineEmits(['onChange', 'onEditPrompt', 'onAddPrompt'])

const props = defineProps({
  prompts: {
    type: Array,
    required: true,
    default: () => [],
  },
  selectedIndex: {
    type: Number,
    default: -1,
  },
})

const handleSelectPropmt = index => {
  emits('onChange', {
    index,
    prompt: toRaw(props.prompts[index]),
  })
}

const handleEditPrompt = index => {
  emits('onEditPrompt', {
    index,
    prompt: toRaw(props.prompts[index]),
  })
}

const handleAddPrompt = () => {
  emits('onAddPrompt')
}
</script>

<style lang="scss" module>
.promptList {
  display: flex;
  height: 24px;
  margin-top: 4px !important;
  margin-bottom: 8px !important;
  color: black;
  font-size: 12px;
  line-height: 17px;
}

.propmtItem + .propmtItem {
  margin-left: 8px !important;
}
</style>

// src/tabs/prompt-board/preset-panel/prompt-list.tsx
import css from 'styled-jsx/css'

import {defaultConfig} from '@/config'

import useConfig from '@/hooks/use-config'
import useAI from '@/hooks/use-ai'

import Button from '@/components/button'

export default function PromptList({
  onSelect = () => null,
  selectIndex = -1,
  updateIndex = () => null,
}) {
  const {config, setConfig} = useConfig()
  const {ai} = useAI()

  const prompts = config.prompts || defaultConfig.prompts

  const selectPrompt = index => {
    updateIndex(index)
    setConfig({...config, latestPresetPromptIndex: index})
    onSelect(prompts[index])
  }

  return (
    <section className="prompt-list">
      {prompts.map((prompt, index) => (
        <div key={index} className="item">
          <Button
            height='25px'
            text={prompt.title}
            disabled={ai?.loading}
            selected={index === selectIndex}
            onClick={() => selectPrompt(index)}
          />
        </div>
      ))}
      <style jsx>{styles}</style>
    </section>
  )
}

const styles = css`
  .prompt-list {
    display: flex;
    flex-wrap: wrap;
    margin-top: 8px;
  }

  .item {
    & + .item {
      margin-left: 8px;
    }

    button {
      padding: 4px 8px;
      color: #4f5aff;
      font-weight: 500;
      font-size: 12px;
      line-height: 17px;
    }
  }

  .custom {
    width: 100%;
    text-align: left;
  }
`
